defaults:
    - agent: sac

taskid: 1

seed: 3

env: gym_pendulum
#
## this needs to be specified manually
experiment: gym_pendulum

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

# warm start
num_seed_steps: 5000

eval_frequency: 1000
num_eval_episodes: 5

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: false


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}